# -*- coding: utf-8 -*-
"""task3_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Y9ZPpIVbn0vwIQ6r-rpR173NPNEASkj
"""

import requests
import json
import time
import os
from datetime import datetime

# --- LOGIC EXPLANATION ---
# 1. Directory Setup: Ensure the 'data/' folder exists for storage.
# 2. Category Keywords: Map specific keywords to categories for filtering titles.
# 3. Step 1 (API): Fetch the top 500 story IDs from the HackerNews topstories endpoint.
# 4. Step 2 (Filtering): Loop through stories, fetch details, and categorize by keyword.
# 5. Constraints: Limit each category to 25 stories (Max 125 total).
# 6. Step 3 (Storage): Save all collected data into a timestamped JSON file.

# Create data directory if it doesn't exist
if not os.path.exists('data'):
    os.makedirs('data')

# Required Header
headers = {"User-Agent": "TrendPulse/1.0"}

# Category Keywords mapping
keywords_map = {
    "technology": ["AI", "software", "tech", "code", "computer", "data", "cloud", "API", "GPU", "LLM"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["NFL", "NBA", "FIFA", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "NASA", "genome"],
    "entertainment": ["movie", "film", "music", "Netflix", "game", "book", "show", "award", "streaming"]
}

def start_collection():
    my_data = []
    category_counts = {cat: 0 for cat in keywords_map}

    print("Step 1: Fetching top story IDs...")
    try:
        # Fetching the first 500 IDs as requested in Step 1
        top_ids_url = "https://hacker-news.firebaseio.com/v0/topstories.json"
        id_response = requests.get(top_ids_url, headers=headers, timeout=15)
        story_ids = id_response.json()[:500]
    except Exception as e:
        print(f"Failed to fetch story IDs: {e}")
        return

    # Step 2: Get story details and categorize
    for category, tags in keywords_map.items():
        print(f"Processing Category: {category}...")

        for s_id in story_ids:
            # Stop if we hit the limit of 25 stories per category
            if category_counts[category] >= 25:
                break

            try:
                # Fetching details for specific ID as requested in Step 2
                item_url = f"https://hacker-news.firebaseio.com/v0/item/{s_id}.json"
                story_res = requests.get(item_url, headers=headers, timeout=5)
                story = story_res.json()

                if not story or 'title' not in story:
                    continue

                title = story.get('title', '')
                # Case-insensitive keyword check
                if any(tag.lower() in title.lower() for tag in tags):
                    # Store exactly the 7 fields required
                    story_record = {
                        "post_id": story.get('id'),
                        "title": title,
                        "category": category,
                        "score": story.get('score', 0),
                        "num_comments": story.get('descendants', 0),
                        "author": story.get('by'),
                        "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                    }
                    my_data.append(story_record)
                    category_counts[category] += 1
            except:
                # Print message and move on if request fails (Task requirement)
                print(f"Request failed for ID {s_id}. Moving to next...")
                continue

        # Rule: Wait 2 seconds between each category loop
        print(f"Finished {category}. Sleeping for 2 seconds...")
        time.sleep(2)

    # Step 3: Save to JSON File
    timestamp = datetime.now().strftime("%Y%m%d")
    json_filename = f"data/trends_{timestamp}.json"

    with open(json_filename, 'w') as f:
        json.dump(my_data, f, indent=4)

    print(f"\nCollected {len(my_data)} stories total.")
    print(f"Saved to {json_filename}")

if __name__ == "__main__":
    start_collection()

import pandas as pd
import os
import glob

# --- LOGIC ---
# Task 2: Cleaning the raw JSON data.
# We load the JSON, remove duplicates/low scores, and save it as a clean CSV.

def start_cleaning():
    # Find the Task 1 JSON file
    path = "data/trends_*.json"
    files = glob.glob(path)

    if not files:
        print("Error: JSON file not found in 'data/' folder. Please run Task 1 first.")
        return

    target_file = files[0] # Takes the most recent file
    print(f"Loading: {target_file}")

    # 1. Load JSON into Pandas
    df = pd.read_json(target_file)
    print(f"Loaded {len(df)} stories.")

    # 2. Cleaning Data
    # Making sure we don't have the same post twice
    df = df.drop_duplicates(subset=['post_id'])

    # Remove missing values
    df = df.dropna(subset=['post_id', 'title', 'score'])

    # Strip spaces from title
    df['title'] = df['title'].str.strip()

    # Filter low quality (Score < 5)
    df = df[df['score'] >= 5]

    # Convert types to integer
    df['score'] = df['score'].astype(int)
    df['num_comments'] = df['num_comments'].astype(int)

    print(f"Rows remaining after cleaning: {len(df)}")

    # Finally exporting the cleaned data to a csv file
    output_path = "data/trends_clean.csv"
    df.to_csv(output_path, index=False)

    print(f" Saved to {output_path}")
    print("\nSummary per category:")
    print(df['category'].value_counts())

if __name__ == "__main__":
    start_cleaning()

import pandas as pd
import numpy as np

# --- MY ANALYSIS LOGIC ---
# 1. Loading the clean data we got from Task 2.
# 2. Using NumPy to calculate the math (Mean, Median, Max, etc.).
# 3. Adding two new columns: 'engagement' (ratio) and 'is_popular' (boolean).
# 4. Exporting the final data to a new CSV file for visualization.

def start_data_study():
    # Load the clean dataset
    source = 'data/trends_clean.csv'

    # Check if the file exists before moving forward
    try:
        trends_df = pd.read_csv(source)
    except:
        print("CSV file missing! Make sure Task 2 is done.")
        return

    # Basic Exploration
    print(f"Data Loaded successfully. Shape: {trends_df.shape}")
    print("\nPreview of first 5 rows:")
    print(trends_df.head())

    # Average metrics using Pandas
    mean_val = trends_df['score'].mean()
    print(f"\nOverall Average Score: {mean_val:.2f}")
    print(f"Overall Average Comments: {trends_df['num_comments'].mean():.2f}")

    # Calculations using NumPy as required
    score_array = trends_df['score'].to_numpy()

    print("\n--- Statistics Summary (NumPy) ---")
    print(f"Average (Mean) : {np.mean(score_array):.2f}")
    print(f"Middle (Median): {np.median(score_array):.2f}")
    print(f"Standard Dev   : {np.std(score_array):.2f}")
    print(f"Highest Score  : {np.max(score_array)}")
    print(f"Lowest Score   : {np.min(score_array)}")

    # Finding patterns
    top_cat = trends_df['category'].value_counts().idxmax()
    print(f"\nCategory with most news: {top_cat}")

    # Finding the story with the peak number of comments
    top_comm_row = trends_df.loc[trends_df['num_comments'].idxmax()]
    print(f"Story with most comments: '{top_comm_row['title']}' ({top_comm_row['num_comments']} comments)")

    # Creating New Metric Columns
    # Engagement: how many comments per upvote
    trends_df['engagement'] = trends_df['num_comments'] / (trends_df['score'] + 1)

    # Popularity: comparing score to the average
    trends_df['is_popular'] = trends_df['score'] > mean_val

    # Save the updated data
    final_path = 'data/trends_analysed.csv'
    trends_df.to_csv(final_path, index=False)
    print(f"\nTask 3 Complete! Results saved to {final_path}")

# Run the study
if __name__ == "__main__":
    start_data_study()